### ISSUE TITLE
AttributeError: TRAINING_IMAGES

### ISSUE THREAD

**Issue by Rocky1salady-killer** [zdaxie/Transformer-Self-Supervised#14]
Traceback (most recent call last):
  File "main.py", line 347, in <module>
    main(config)
  File "main.py", line 80, in main
    model = build_model(config)
  File "/home/featurize/work/STSL/models/build.py", line 65, in build_model
    pred_num_layers=config.MODEL.MOBY.PRED_NUM_LAYERS,
  File "/home/featurize/work/STSL/models/moby.py", line 77, in __init__
    self.K = int(self.cfg.DATA.TRAINING_IMAGES * 1. / dist.get_world_size()  / self.cfg.DATA.BATCH_SIZE) * self.cfg.TRAIN.EPOCHS
  File "/environment/miniconda3/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: TRAINING_IMAGES

hallo everone！How to solve this problem?

**Comment by Kane-0516** [comment]
I also met this problem. How did you solve it?
